# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prototype.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameControl = QtWidgets.QFrame(self.centralwidget)
        self.frameControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameControl.setObjectName("frameControl")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frameControl)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.listViewPacketStack = QtWidgets.QListView(self.frameControl)
        self.listViewPacketStack.setObjectName("listViewPacketStack")
        self.gridLayout_9.addWidget(self.listViewPacketStack, 2, 0, 1, 3)
        self.pushButtonSend = QtWidgets.QPushButton(self.frameControl)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.gridLayout_9.addWidget(self.pushButtonSend, 1, 2, 1, 1)
        self.pushButtonAddPacket = QtWidgets.QPushButton(self.frameControl)
        self.pushButtonAddPacket.setObjectName("pushButtonAddPacket")
        self.gridLayout_9.addWidget(self.pushButtonAddPacket, 1, 0, 1, 1)
        self.pushButtonDeletePacket = QtWidgets.QPushButton(self.frameControl)
        self.pushButtonDeletePacket.setObjectName("pushButtonDeletePacket")
        self.gridLayout_9.addWidget(self.pushButtonDeletePacket, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frameControl, 0, 3, 1, 1)
        self.frameOptions = QtWidgets.QFrame(self.centralwidget)
        self.frameOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOptions.setObjectName("frameOptions")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frameOptions)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidgetEther = QtWidgets.QTabWidget(self.frameOptions)
        self.tabWidgetEther.setMinimumSize(QtCore.QSize(0, 170))
        self.tabWidgetEther.setObjectName("tabWidgetEther")
        self.tabEther = QtWidgets.QWidget()
        self.tabEther.setObjectName("tabEther")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabEther)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tabEther)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 539, 123))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditEtherType = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditEtherType.setObjectName("lineEditEtherType")
        self.gridLayout.addWidget(self.lineEditEtherType, 5, 1, 1, 1)
        self.comboBoxEtherDst = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxEtherDst.setObjectName("comboBoxEtherDst")
        self.gridLayout.addWidget(self.comboBoxEtherDst, 4, 2, 1, 1)
        self.lineEditEtherDst = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditEtherDst.setObjectName("lineEditEtherDst")
        self.gridLayout.addWidget(self.lineEditEtherDst, 4, 1, 1, 1)
        self.comboBoxEtherType = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxEtherType.setObjectName("comboBoxEtherType")
        self.gridLayout.addWidget(self.comboBoxEtherType, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEditEtherSrc = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditEtherSrc.setObjectName("lineEditEtherSrc")
        self.gridLayout.addWidget(self.lineEditEtherSrc, 3, 1, 1, 1)
        self.comboBoxEtherSrc = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxEtherSrc.setObjectName("comboBoxEtherSrc")
        self.gridLayout.addWidget(self.comboBoxEtherSrc, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 1, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tabWidgetEther.addTab(self.tabEther, "")
        self.gridLayout_8.addWidget(self.tabWidgetEther, 0, 0, 1, 1)
        self.tabWidgetICMPTCPUDP = QtWidgets.QTabWidget(self.frameOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetICMPTCPUDP.sizePolicy().hasHeightForWidth())
        self.tabWidgetICMPTCPUDP.setSizePolicy(sizePolicy)
        self.tabWidgetICMPTCPUDP.setObjectName("tabWidgetICMPTCPUDP")
        self.tabICMP = QtWidgets.QWidget()
        self.tabICMP.setObjectName("tabICMP")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabICMP)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tabICMP)
        self.scrollArea_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, -44, 539, 403))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 4, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_56.setObjectName("label_56")
        self.gridLayout_11.addWidget(self.label_56, 5, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_61.setObjectName("label_61")
        self.gridLayout_11.addWidget(self.label_61, 8, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_57.setObjectName("label_57")
        self.gridLayout_11.addWidget(self.label_57, 6, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_60.setObjectName("label_60")
        self.gridLayout_11.addWidget(self.label_60, 7, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_62.setObjectName("label_62")
        self.gridLayout_11.addWidget(self.label_62, 9, 0, 1, 1)
        self.lineEditICMPSeq = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPSeq.setObjectName("lineEditICMPSeq")
        self.gridLayout_11.addWidget(self.lineEditICMPSeq, 6, 1, 1, 1)
        self.lineEditICMPChksum = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPChksum.setObjectName("lineEditICMPChksum")
        self.gridLayout_11.addWidget(self.lineEditICMPChksum, 4, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_63.setObjectName("label_63")
        self.gridLayout_11.addWidget(self.label_63, 10, 0, 1, 1)
        self.lineEditICMPCode = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPCode.setObjectName("lineEditICMPCode")
        self.gridLayout_11.addWidget(self.lineEditICMPCode, 3, 1, 1, 1)
        self.comboBoxICMPType = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPType.setObjectName("comboBoxICMPType")
        self.gridLayout_11.addWidget(self.comboBoxICMPType, 1, 2, 1, 1)
        self.comboBoxICMPCode = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPCode.setObjectName("comboBoxICMPCode")
        self.gridLayout_11.addWidget(self.comboBoxICMPCode, 3, 2, 1, 1)
        self.lineEditICMPType = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPType.setObjectName("lineEditICMPType")
        self.gridLayout_11.addWidget(self.lineEditICMPType, 1, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_64.setObjectName("label_64")
        self.gridLayout_11.addWidget(self.label_64, 11, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_58.setObjectName("label_58")
        self.gridLayout_11.addWidget(self.label_58, 1, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_59.setObjectName("label_59")
        self.gridLayout_11.addWidget(self.label_59, 3, 0, 1, 1)
        self.comboBoxICMPChksum = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPChksum.setObjectName("comboBoxICMPChksum")
        self.gridLayout_11.addWidget(self.comboBoxICMPChksum, 4, 2, 1, 1)
        self.lineEditICMPId = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPId.setObjectName("lineEditICMPId")
        self.gridLayout_11.addWidget(self.lineEditICMPId, 5, 1, 1, 1)
        self.lineEditICMPTs_ori = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPTs_ori.setObjectName("lineEditICMPTs_ori")
        self.gridLayout_11.addWidget(self.lineEditICMPTs_ori, 7, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_65.setObjectName("label_65")
        self.gridLayout_11.addWidget(self.label_65, 0, 0, 1, 1)
        self.lineEditICMPPtr = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPPtr.setObjectName("lineEditICMPPtr")
        self.gridLayout_11.addWidget(self.lineEditICMPPtr, 11, 1, 1, 1)
        self.lineEditICMPTs_rx = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPTs_rx.setObjectName("lineEditICMPTs_rx")
        self.gridLayout_11.addWidget(self.lineEditICMPTs_rx, 8, 1, 1, 1)
        self.comboBoxICMPTs_ori = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPTs_ori.setObjectName("comboBoxICMPTs_ori")
        self.gridLayout_11.addWidget(self.comboBoxICMPTs_ori, 7, 2, 1, 1)
        self.lineEditICMPTs_tx = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPTs_tx.setObjectName("lineEditICMPTs_tx")
        self.gridLayout_11.addWidget(self.lineEditICMPTs_tx, 9, 1, 1, 1)
        self.lineEditICMPGw = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPGw.setObjectName("lineEditICMPGw")
        self.gridLayout_11.addWidget(self.lineEditICMPGw, 10, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_66.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_11.addWidget(self.label_66, 0, 1, 1, 1)
        self.comboBoxICMPSeq = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPSeq.setObjectName("comboBoxICMPSeq")
        self.gridLayout_11.addWidget(self.comboBoxICMPSeq, 6, 2, 1, 1)
        self.comboBoxICMPId = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPId.setObjectName("comboBoxICMPId")
        self.gridLayout_11.addWidget(self.comboBoxICMPId, 5, 2, 1, 1)
        self.comboBoxICMPTs_tx = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPTs_tx.setObjectName("comboBoxICMPTs_tx")
        self.gridLayout_11.addWidget(self.comboBoxICMPTs_tx, 9, 2, 1, 1)
        self.comboBoxICMPTs_rx = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPTs_rx.setObjectName("comboBoxICMPTs_rx")
        self.gridLayout_11.addWidget(self.comboBoxICMPTs_rx, 8, 2, 1, 1)
        self.comboBoxICMPGw = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPGw.setObjectName("comboBoxICMPGw")
        self.gridLayout_11.addWidget(self.comboBoxICMPGw, 10, 2, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_67.setObjectName("label_67")
        self.gridLayout_11.addWidget(self.label_67, 0, 2, 1, 1)
        self.comboBoxICMPPtr = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPPtr.setObjectName("comboBoxICMPPtr")
        self.gridLayout_11.addWidget(self.comboBoxICMPPtr, 11, 2, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_69.setObjectName("label_69")
        self.gridLayout_11.addWidget(self.label_69, 13, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_68.setObjectName("label_68")
        self.gridLayout_11.addWidget(self.label_68, 12, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_70.setObjectName("label_70")
        self.gridLayout_11.addWidget(self.label_70, 14, 0, 1, 1)
        self.lineEditICMPReserved = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPReserved.setObjectName("lineEditICMPReserved")
        self.gridLayout_11.addWidget(self.lineEditICMPReserved, 12, 1, 1, 1)
        self.lineEditICMPAddr_mask = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPAddr_mask.setObjectName("lineEditICMPAddr_mask")
        self.gridLayout_11.addWidget(self.lineEditICMPAddr_mask, 13, 1, 1, 1)
        self.lineEditICMPUnused = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditICMPUnused.setObjectName("lineEditICMPUnused")
        self.gridLayout_11.addWidget(self.lineEditICMPUnused, 14, 1, 1, 1)
        self.comboBoxICMPReserved = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPReserved.setObjectName("comboBoxICMPReserved")
        self.gridLayout_11.addWidget(self.comboBoxICMPReserved, 12, 2, 1, 1)
        self.comboBoxICMPAddr_mask = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPAddr_mask.setObjectName("comboBoxICMPAddr_mask")
        self.gridLayout_11.addWidget(self.comboBoxICMPAddr_mask, 13, 2, 1, 1)
        self.comboBoxICMPUnused = QtWidgets.QComboBox(self.scrollAreaWidgetContents_6)
        self.comboBoxICMPUnused.setObjectName("comboBoxICMPUnused")
        self.gridLayout_11.addWidget(self.comboBoxICMPUnused, 14, 2, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_7.addWidget(self.scrollArea_6, 0, 0, 1, 1)
        self.tabWidgetICMPTCPUDP.addTab(self.tabICMP, "")
        self.tabTCP = QtWidgets.QWidget()
        self.tabTCP.setObjectName("tabTCP")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tabTCP)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tabTCP)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 539, 347))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 4, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 7, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 9, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 8, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 2, 0, 1, 1)
        self.lineEditTCPChksum = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPChksum.setObjectName("lineEditTCPChksum")
        self.gridLayout_6.addWidget(self.lineEditTCPChksum, 11, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 0, 3, 1, 1)
        self.lineEditTCPDport = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPDport.setObjectName("lineEditTCPDport")
        self.gridLayout_6.addWidget(self.lineEditTCPDport, 2, 3, 1, 1)
        self.lineEditTCPUrgptr = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPUrgptr.setObjectName("lineEditTCPUrgptr")
        self.gridLayout_6.addWidget(self.lineEditTCPUrgptr, 12, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 12, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 10, 0, 1, 1)
        self.lineEditTCPSeq = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPSeq.setObjectName("lineEditTCPSeq")
        self.gridLayout_6.addWidget(self.lineEditTCPSeq, 3, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 11, 0, 1, 1)
        self.lineEditTCPReserved = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPReserved.setObjectName("lineEditTCPReserved")
        self.gridLayout_6.addWidget(self.lineEditTCPReserved, 8, 3, 1, 1)
        self.lineEditTCPFlags = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPFlags.setObjectName("lineEditTCPFlags")
        self.gridLayout_6.addWidget(self.lineEditTCPFlags, 9, 3, 1, 1)
        self.lineEditTCPWindow = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPWindow.setObjectName("lineEditTCPWindow")
        self.gridLayout_6.addWidget(self.lineEditTCPWindow, 10, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 0, 0, 1, 1)
        self.lineEditTCPOptions = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPOptions.setObjectName("lineEditTCPOptions")
        self.gridLayout_6.addWidget(self.lineEditTCPOptions, 13, 3, 1, 1)
        self.lineEditTCPAck = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPAck.setObjectName("lineEditTCPAck")
        self.gridLayout_6.addWidget(self.lineEditTCPAck, 4, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 13, 0, 1, 1)
        self.lineEditTCPDataofs = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPDataofs.setObjectName("lineEditTCPDataofs")
        self.gridLayout_6.addWidget(self.lineEditTCPDataofs, 7, 3, 1, 1)
        self.lineEditTCPSport = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEditTCPSport.setObjectName("lineEditTCPSport")
        self.gridLayout_6.addWidget(self.lineEditTCPSport, 1, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 0, 4, 1, 1)
        self.comboBoxTCPSport = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPSport.setObjectName("comboBoxTCPSport")
        self.gridLayout_6.addWidget(self.comboBoxTCPSport, 1, 4, 1, 1)
        self.comboBoxTCPSeq = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPSeq.setObjectName("comboBoxTCPSeq")
        self.gridLayout_6.addWidget(self.comboBoxTCPSeq, 3, 4, 1, 1)
        self.comboBoxTCPDport = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPDport.setObjectName("comboBoxTCPDport")
        self.gridLayout_6.addWidget(self.comboBoxTCPDport, 2, 4, 1, 1)
        self.comboBoxTCPAck = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPAck.setObjectName("comboBoxTCPAck")
        self.gridLayout_6.addWidget(self.comboBoxTCPAck, 4, 4, 1, 1)
        self.comboBoxTCPDataofs = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPDataofs.setObjectName("comboBoxTCPDataofs")
        self.gridLayout_6.addWidget(self.comboBoxTCPDataofs, 7, 4, 1, 1)
        self.comboBoxTCPReserved = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPReserved.setObjectName("comboBoxTCPReserved")
        self.gridLayout_6.addWidget(self.comboBoxTCPReserved, 8, 4, 1, 1)
        self.comboBoxTCPFlags = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPFlags.setObjectName("comboBoxTCPFlags")
        self.gridLayout_6.addWidget(self.comboBoxTCPFlags, 9, 4, 1, 1)
        self.comboBoxTCPWindow = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPWindow.setObjectName("comboBoxTCPWindow")
        self.gridLayout_6.addWidget(self.comboBoxTCPWindow, 10, 4, 1, 1)
        self.comboBoxTCPChksum = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPChksum.setObjectName("comboBoxTCPChksum")
        self.gridLayout_6.addWidget(self.comboBoxTCPChksum, 11, 4, 1, 1)
        self.comboBoxTCPUrgptr = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPUrgptr.setObjectName("comboBoxTCPUrgptr")
        self.gridLayout_6.addWidget(self.comboBoxTCPUrgptr, 12, 4, 1, 1)
        self.comboBoxTCPOptions = QtWidgets.QComboBox(self.scrollAreaWidgetContents_5)
        self.comboBoxTCPOptions.setObjectName("comboBoxTCPOptions")
        self.gridLayout_6.addWidget(self.comboBoxTCPOptions, 13, 4, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_6.addWidget(self.scrollArea_5)
        self.tabWidgetICMPTCPUDP.addTab(self.tabTCP, "")
        self.tabUDP = QtWidgets.QWidget()
        self.tabUDP.setObjectName("tabUDP")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabUDP)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tabUDP)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 560, 167))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 7, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 8, 0, 1, 1)
        self.lineEditUDPDport = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEditUDPDport.setObjectName("lineEditUDPDport")
        self.gridLayout_5.addWidget(self.lineEditUDPDport, 6, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 6, 0, 1, 1)
        self.comboBoxUDPLen = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.comboBoxUDPLen.setObjectName("comboBoxUDPLen")
        self.gridLayout_5.addWidget(self.comboBoxUDPLen, 7, 2, 1, 1)
        self.lineEditUDPChksum = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEditUDPChksum.setObjectName("lineEditUDPChksum")
        self.gridLayout_5.addWidget(self.lineEditUDPChksum, 8, 1, 1, 1)
        self.comboBoxUDPChksum = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.comboBoxUDPChksum.setObjectName("comboBoxUDPChksum")
        self.gridLayout_5.addWidget(self.comboBoxUDPChksum, 8, 2, 1, 1)
        self.lineEditUDPSport = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEditUDPSport.setObjectName("lineEditUDPSport")
        self.gridLayout_5.addWidget(self.lineEditUDPSport, 4, 1, 1, 1)
        self.lineEditUDPLen = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEditUDPLen.setObjectName("lineEditUDPLen")
        self.gridLayout_5.addWidget(self.lineEditUDPLen, 7, 1, 1, 1)
        self.comboBoxUDPDport = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.comboBoxUDPDport.setObjectName("comboBoxUDPDport")
        self.gridLayout_5.addWidget(self.comboBoxUDPDport, 6, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 2, 0, 1, 1)
        self.comboBoxUDPSport = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.comboBoxUDPSport.setObjectName("comboBoxUDPSport")
        self.gridLayout_5.addWidget(self.comboBoxUDPSport, 4, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 2, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 4, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_5.addWidget(self.scrollArea_4)
        self.tabWidgetICMPTCPUDP.addTab(self.tabUDP, "")
        self.gridLayout_8.addWidget(self.tabWidgetICMPTCPUDP, 2, 0, 1, 1)
        self.tabWidgetARPIP = QtWidgets.QTabWidget(self.frameOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetARPIP.sizePolicy().hasHeightForWidth())
        self.tabWidgetARPIP.setSizePolicy(sizePolicy)
        self.tabWidgetARPIP.setMinimumSize(QtCore.QSize(0, 300))
        self.tabWidgetARPIP.setObjectName("tabWidgetARPIP")
        self.tabARP = QtWidgets.QWidget()
        self.tabARP.setObjectName("tabARP")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabARP)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tabARP)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 539, 328))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBoxARPPsrc = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPPsrc.setObjectName("comboBoxARPPsrc")
        self.gridLayout_3.addWidget(self.comboBoxARPPsrc, 7, 2, 1, 1)
        self.lineEditARPHwlen = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPHwlen.setObjectName("lineEditARPHwlen")
        self.gridLayout_3.addWidget(self.lineEditARPHwlen, 3, 1, 1, 1)
        self.lineEditARPOp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPOp.setObjectName("lineEditARPOp")
        self.gridLayout_3.addWidget(self.lineEditARPOp, 5, 1, 1, 1)
        self.lineEditARPPtype = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPPtype.setObjectName("lineEditARPPtype")
        self.gridLayout_3.addWidget(self.lineEditARPPtype, 2, 1, 1, 1)
        self.lineEditARPPdst = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPPdst.setObjectName("lineEditARPPdst")
        self.gridLayout_3.addWidget(self.lineEditARPPdst, 9, 1, 1, 1)
        self.comboBoxARPPdst = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPPdst.setObjectName("comboBoxARPPdst")
        self.gridLayout_3.addWidget(self.comboBoxARPPdst, 9, 2, 1, 1)
        self.comboBoxARPHwdst = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPHwdst.setObjectName("comboBoxARPHwdst")
        self.gridLayout_3.addWidget(self.comboBoxARPHwdst, 8, 2, 1, 1)
        self.lineEditARPHwsrc = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPHwsrc.setObjectName("lineEditARPHwsrc")
        self.gridLayout_3.addWidget(self.lineEditARPHwsrc, 6, 1, 1, 1)
        self.lineEditARPPlen = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPPlen.setObjectName("lineEditARPPlen")
        self.gridLayout_3.addWidget(self.lineEditARPPlen, 4, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_48.setMinimumSize(QtCore.QSize(0, 54))
        self.label_48.setObjectName("label_48")
        self.gridLayout_3.addWidget(self.label_48, 0, 2, 1, 1)
        self.lineEditARPHwtype = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPHwtype.setObjectName("lineEditARPHwtype")
        self.gridLayout_3.addWidget(self.lineEditARPHwtype, 1, 1, 1, 1)
        self.lineEditARPHwdst = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPHwdst.setObjectName("lineEditARPHwdst")
        self.gridLayout_3.addWidget(self.lineEditARPHwdst, 8, 1, 1, 1)
        self.lineEditARPPsrc = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEditARPPsrc.setObjectName("lineEditARPPsrc")
        self.gridLayout_3.addWidget(self.lineEditARPPsrc, 7, 1, 1, 1)
        self.comboBoxARPPtype = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPPtype.setObjectName("comboBoxARPPtype")
        self.gridLayout_3.addWidget(self.comboBoxARPPtype, 2, 2, 1, 1)
        self.comboBoxARPHwsrc = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPHwsrc.setObjectName("comboBoxARPHwsrc")
        self.gridLayout_3.addWidget(self.comboBoxARPHwsrc, 6, 2, 1, 1)
        self.comboBoxARPOp = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPOp.setObjectName("comboBoxARPOp")
        self.gridLayout_3.addWidget(self.comboBoxARPOp, 5, 2, 1, 1)
        self.comboBoxARPPlen = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPPlen.setObjectName("comboBoxARPPlen")
        self.gridLayout_3.addWidget(self.comboBoxARPPlen, 4, 2, 1, 1)
        self.comboBoxARPHwlen = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPHwlen.setObjectName("comboBoxARPHwlen")
        self.gridLayout_3.addWidget(self.comboBoxARPHwlen, 3, 2, 1, 1)
        self.comboBoxARPHwtype = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.comboBoxARPHwtype.setObjectName("comboBoxARPHwtype")
        self.gridLayout_3.addWidget(self.comboBoxARPHwtype, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_46.setObjectName("label_46")
        self.gridLayout_3.addWidget(self.label_46, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_47.setObjectName("label_47")
        self.gridLayout_3.addWidget(self.label_47, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 7, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.addWidget(self.scrollArea_3)
        self.tabWidgetARPIP.addTab(self.tabARP, "")
        self.tabIP = QtWidgets.QWidget()
        self.tabIP.setObjectName("tabIP")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabIP)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabIP)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -84, 539, 375))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 0, 1, 1)
        self.comboBoxIPChecksum = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPChecksum.setObjectName("comboBoxIPChecksum")
        self.gridLayout_4.addWidget(self.comboBoxIPChecksum, 14, 2, 1, 1)
        self.lineEditIPVersion = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPVersion.setObjectName("lineEditIPVersion")
        self.gridLayout_4.addWidget(self.lineEditIPVersion, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 15, 0, 1, 1)
        self.lineEditIPSrc = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPSrc.setObjectName("lineEditIPSrc")
        self.gridLayout_4.addWidget(self.lineEditIPSrc, 15, 1, 1, 1)
        self.lineEditIPChecksum = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPChecksum.setObjectName("lineEditIPChecksum")
        self.gridLayout_4.addWidget(self.lineEditIPChecksum, 14, 1, 1, 1)
        self.lineEditIPDst = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPDst.setObjectName("lineEditIPDst")
        self.gridLayout_4.addWidget(self.lineEditIPDst, 16, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 0, 1, 1, 1)
        self.lineEditIPTtl = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPTtl.setObjectName("lineEditIPTtl")
        self.gridLayout_4.addWidget(self.lineEditIPTtl, 10, 1, 1, 1)
        self.comboBoxIPDst = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPDst.setObjectName("comboBoxIPDst")
        self.gridLayout_4.addWidget(self.comboBoxIPDst, 16, 2, 1, 1)
        self.lineEditIPFragment = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPFragment.setObjectName("lineEditIPFragment")
        self.gridLayout_4.addWidget(self.lineEditIPFragment, 9, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 14, 0, 1, 1)
        self.lineEditIPProto = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPProto.setObjectName("lineEditIPProto")
        self.gridLayout_4.addWidget(self.lineEditIPProto, 12, 1, 1, 1)
        self.lineEditIPFlags = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPFlags.setObjectName("lineEditIPFlags")
        self.gridLayout_4.addWidget(self.lineEditIPFlags, 6, 1, 1, 1)
        self.lineEditIPTos = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPTos.setObjectName("lineEditIPTos")
        self.gridLayout_4.addWidget(self.lineEditIPTos, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 10, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 12, 0, 1, 1)
        self.lineEditIPId = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPId.setObjectName("lineEditIPId")
        self.gridLayout_4.addWidget(self.lineEditIPId, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 16, 0, 1, 1)
        self.lineEditIPLength = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPLength.setObjectName("lineEditIPLength")
        self.gridLayout_4.addWidget(self.lineEditIPLength, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 9, 0, 1, 1)
        self.lineEditIPIhl = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEditIPIhl.setObjectName("lineEditIPIhl")
        self.gridLayout_4.addWidget(self.lineEditIPIhl, 2, 1, 1, 1)
        self.comboBoxIPFlags = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPFlags.setObjectName("comboBoxIPFlags")
        self.gridLayout_4.addWidget(self.comboBoxIPFlags, 6, 2, 1, 1)
        self.comboBoxIPSrc = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPSrc.setObjectName("comboBoxIPSrc")
        self.gridLayout_4.addWidget(self.comboBoxIPSrc, 15, 2, 1, 1)
        self.comboBoxIPVersion = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPVersion.setObjectName("comboBoxIPVersion")
        self.gridLayout_4.addWidget(self.comboBoxIPVersion, 1, 2, 1, 1)
        self.comboBoxIPFragment = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPFragment.setObjectName("comboBoxIPFragment")
        self.gridLayout_4.addWidget(self.comboBoxIPFragment, 9, 2, 1, 1)
        self.comboBoxIPIhl = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPIhl.setObjectName("comboBoxIPIhl")
        self.gridLayout_4.addWidget(self.comboBoxIPIhl, 2, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 0, 2, 1, 1)
        self.comboBoxIPTtl = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPTtl.setObjectName("comboBoxIPTtl")
        self.gridLayout_4.addWidget(self.comboBoxIPTtl, 10, 2, 1, 1)
        self.comboBoxIPProto = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPProto.setObjectName("comboBoxIPProto")
        self.gridLayout_4.addWidget(self.comboBoxIPProto, 12, 2, 1, 1)
        self.comboBoxIPTos = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPTos.setObjectName("comboBoxIPTos")
        self.gridLayout_4.addWidget(self.comboBoxIPTos, 3, 2, 1, 1)
        self.comboBoxIPLength = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPLength.setObjectName("comboBoxIPLength")
        self.gridLayout_4.addWidget(self.comboBoxIPLength, 4, 2, 1, 1)
        self.comboBoxIPId = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBoxIPId.setObjectName("comboBoxIPId")
        self.gridLayout_4.addWidget(self.comboBoxIPId, 5, 2, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.tabWidgetARPIP.addTab(self.tabIP, "")
        self.gridLayout_8.addWidget(self.tabWidgetARPIP, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameOptions, 0, 1, 1, 1)
        self.textBrowserHexdump = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserHexdump.setObjectName("textBrowserHexdump")
        self.gridLayout_2.addWidget(self.textBrowserHexdump, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetEther.setCurrentIndex(0)
        self.tabWidgetICMPTCPUDP.setCurrentIndex(0)
        self.tabWidgetARPIP.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonSend.setText(_translate("MainWindow", "Send"))
        self.pushButtonAddPacket.setText(_translate("MainWindow", "Add Packet"))
        self.pushButtonDeletePacket.setText(_translate("MainWindow", "Delete Packet"))
        self.label_2.setText(_translate("MainWindow", "Destination MAC Address"))
        self.label_3.setText(_translate("MainWindow", "Protocol"))
        self.label.setText(_translate("MainWindow", "Source MAC Address"))
        self.label_49.setText(_translate("MainWindow", "<b>Field Name</b>"))
        self.label_41.setText(_translate("MainWindow", "<b>Value</b>"))
        self.label_42.setText(_translate("MainWindow", "<b>Common Value</b>"))
        self.tabWidgetEther.setTabText(self.tabWidgetEther.indexOf(self.tabEther), _translate("MainWindow", "Ethernet"))
        self.label_55.setText(_translate("MainWindow", "Checksum"))
        self.label_56.setText(_translate("MainWindow", "ID"))
        self.label_61.setText(_translate("MainWindow", "Timestamp Receive"))
        self.label_57.setText(_translate("MainWindow", "Sequential Number"))
        self.label_60.setText(_translate("MainWindow", "Timestamp Originate"))
        self.label_62.setText(_translate("MainWindow", "Timestamp Transmit"))
        self.label_63.setText(_translate("MainWindow", "Gateway"))
        self.label_64.setText(_translate("MainWindow", "Pointer"))
        self.label_58.setText(_translate("MainWindow", "Type"))
        self.label_59.setText(_translate("MainWindow", "Code"))
        self.label_65.setText(_translate("MainWindow", "<b>Field Name</b>"))
        self.label_66.setText(_translate("MainWindow", "<b>Value</b>"))
        self.label_67.setText(_translate("MainWindow", "<b>Common Value</b>"))
        self.label_69.setText(_translate("MainWindow", "Address Mask"))
        self.label_68.setText(_translate("MainWindow", "Reserved"))
        self.label_70.setText(_translate("MainWindow", "Unused"))
        self.tabWidgetICMPTCPUDP.setTabText(self.tabWidgetICMPTCPUDP.indexOf(self.tabICMP), _translate("MainWindow", "ICMP"))
        self.label_29.setText(_translate("MainWindow", "Source Port"))
        self.label_32.setText(_translate("MainWindow", "Acknowledge Number"))
        self.label_33.setText(_translate("MainWindow", "Data Offset"))
        self.label_36.setText(_translate("MainWindow", "Flags"))
        self.label_31.setText(_translate("MainWindow", "Sequential Number"))
        self.label_37.setText(_translate("MainWindow", "Reserved"))
        self.label_30.setText(_translate("MainWindow", "Destination Port"))
        self.label_53.setText(_translate("MainWindow", "<b>Value</b>"))
        self.label_39.setText(_translate("MainWindow", "Urgent Pointer"))
        self.label_35.setText(_translate("MainWindow", "Window Size"))
        self.label_34.setText(_translate("MainWindow", "Checksum"))
        self.label_52.setText(_translate("MainWindow", "<b>Field Name</b>"))
        self.label_38.setText(_translate("MainWindow", "Options"))
        self.label_54.setText(_translate("MainWindow", "<b>Common Value</bcombo>"))
        self.tabWidgetICMPTCPUDP.setTabText(self.tabWidgetICMPTCPUDP.indexOf(self.tabTCP), _translate("MainWindow", "TCP"))
        self.label_28.setText(_translate("MainWindow", "Length"))
        self.label_26.setText(_translate("MainWindow", "Checksum"))
        self.label_27.setText(_translate("MainWindow", "Destination Port"))
        self.label_40.setText(_translate("MainWindow", "<b>Field</b>"))
        self.label_51.setText(_translate("MainWindow", "<b>Common Value</b>"))
        self.label_50.setText(_translate("MainWindow", "<b>Value</b>"))
        self.label_25.setText(_translate("MainWindow", "Source Port"))
        self.tabWidgetICMPTCPUDP.setTabText(self.tabWidgetICMPTCPUDP.indexOf(self.tabUDP), _translate("MainWindow", "UDP"))
        self.label_48.setText(_translate("MainWindow", "<b>Common Value</b>"))
        self.label_9.setText(_translate("MainWindow", "Hardware Type"))
        self.label_4.setText(_translate("MainWindow", "Protocol Type"))
        self.label_12.setText(_translate("MainWindow", "Hardware Address Length"))
        self.label_46.setText(_translate("MainWindow", "<b>Field Name</b>"))
        self.label_11.setText(_translate("MainWindow", "Protocol Address Length"))
        self.label_8.setText(_translate("MainWindow", "Operation Type"))
        self.label_10.setText(_translate("MainWindow", "Hardware Source Address"))
        self.label_47.setText(_translate("MainWindow", "<b>Value</b>"))
        self.label_7.setText(_translate("MainWindow", "Hardware Destination Address"))
        self.label_5.setText(_translate("MainWindow", "Protocol Destination Address"))
        self.label_6.setText(_translate("MainWindow", "Protocol Source Address"))
        self.tabWidgetARPIP.setTabText(self.tabWidgetARPIP.indexOf(self.tabARP), _translate("MainWindow", "ARP"))
        self.label_43.setText(_translate("MainWindow", "<b>Field Name</b>"))
        self.label_16.setText(_translate("MainWindow", "IP Datagram Length"))
        self.label_14.setText(_translate("MainWindow", "IP header length (in 4 bytes)"))
        self.label_18.setText(_translate("MainWindow", "flags"))
        self.label_15.setText(_translate("MainWindow", "Type of Service (unused)"))
        self.label_13.setText(_translate("MainWindow", "IP Version"))
        self.label_17.setText(_translate("MainWindow", "ID"))
        self.label_24.setText(_translate("MainWindow", "Source IP Address"))
        self.label_44.setText(_translate("MainWindow", "<b>Value</b>"))
        self.label_22.setText(_translate("MainWindow", "Checksum"))
        self.label_20.setText(_translate("MainWindow", "Time To Live"))
        self.label_21.setText(_translate("MainWindow", "Protocol"))
        self.label_23.setText(_translate("MainWindow", "Destination IP Address"))
        self.label_19.setText(_translate("MainWindow", "Fragment"))
        self.label_45.setText(_translate("MainWindow", "<b>Common Value</b>"))
        self.tabWidgetARPIP.setTabText(self.tabWidgetARPIP.indexOf(self.tabIP), _translate("MainWindow", "IP"))

